### ISSUE TITLE
Add endpoint to recompute report

### ISSUE THREAD

**Issue by alorenzo175** [SolarArbiter/solarforecastarbiter-api#220]
from the current report parameters retaining the same ID. The periodic report job does this, but would be nice to be able to do it on the fly perhaps via a button on the report page on the dashboard

**Comment by lboeman** [comment]
I'm taking a stab at this, and am using the `get_user_actions_on_object` procedure to check for update perms before scheduling the compute. This may lead to users who don't have the necessary read permissions triggering a recompute and resulting in a failure.
I'd imagine this would only occur when there are two users with report privileges in an organization that have been shared external data separately and have reports using data the other user can't see.
I think this is okay with the current state of the arbiter because a user could create a report that would fail if they didn't have read_values permissions on one of the objects in the first place, but I wanted to see if there are any objections before moving forward.
